version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    links:
      - mysql:db
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - vendor:/app/vendor

  backend:
    build: backend
    ports:
      - 21080:80
    links:
      - mysql:db
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - vendor:/app/vendor

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    volumes:
      - dbv:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    links:
      - frontend:frontend
      - backend:backend

volumes:
  dbv:
  vendor: